### ISSUE TITLE
cannot import name 'BinarySensorDevice' from 'homeassistant.components.binary_sensor' 

### ISSUE THREAD

**Issue by HiTechTLS** [sgowal/badnest#3]
badnest:
  issue_token: SECRET
  cookie: SECRET

sensor:
  - platform: badnest

binary_sensor:
  - platform: badnest

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
platform = p_integration.get_platform(domain)
File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 583, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/config/custom_components/badnest/binary_sensor.py", line 3, in <module>
from homeassistant.components.binary_sensor import (
ImportError: cannot import name 'BinarySensorDevice' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)

**Comment by juliusgaiuscaesar** [comment]
I'm not a coder, but what solved it for me was to update the file /config/custom_components/badnest/binary_sensor.py, by changing all occurrences (3) of 'BinarySensorDevice' into 'BinarySensorEntity'.

**Comment by HiTechTLS** [comment]
Thanks, makes sense to me, but on to next bug

2022-02-07 16:12:00 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration badnest which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**2022-02-07 16:13:09 ERROR (SyncWorker_3) [custom_components.badnest.nest.nest_api] Unable to update streaming devices.
2022-02-07 16:14:09 ERROR (SyncWorker_4) [custom_components.badnest.nest.nest_api] Unable to update streaming devices.**

Bit less verbose. Wonder if its from me running both nest plugins at same time, but the $5 official has been good to me with the thermostat, looking for the protect that isn't supported there and more metadata beyond the high level the google api provides.

**Comment by HiTechTLS** [comment]
jk... seems this is expected failure?

![image](https://user-images.githubusercontent.com/99000979/152874119-2b1a4a52-8476-4392-af3f-44b00ac535f4.png)

![image](https://user-images.githubusercontent.com/99000979/152874196-7fdf914f-236d-4cec-8575-831ee7fa9ed8.png)

**Comment by HiTechTLS** [comment]
Seems those values are all just defaults, and too frightened to light an indoor fire to change the input to my protect!!!

Logger: custom_components.badnest.nest.nest_api
Source: custom_components/badnest/nest/nest_api.py:303
Integration: Bad Nest (Reverse-engineered Nest API) ([documentation](https://github.com/sgowal/badnest))
First occurred: 4:30:28 PM (1 occurrences)
Last logged: 4:30:28 PM

Unable to update streaming devices.

Possibly remove the battery/kill the hardwired power to see if it shows "not-normal"?
